spring:
  application:
    name: myclient
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: info
eureka:
  instance:
    prefer-ip-address: true
  client:
    initialInstanceInfoReplicationIntervalSeconds: 5
    #onDemandUpdateStatusChange: false
    #register-with-eureka: false
    #fetchRegistry: false
    #nonSecurePort: 0
    service-url:
      defaultZone: http://localhost:8080/eureka/
mq:
  queue: demo_01
server:
  port: 8020

management:
  #server:
    #port: 8011
     web:
       exposure:
          include: '*'
endpoints:
  sensitive: false
test:
  param: test003